### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by SunDi3yansyah** [nurisakbar/siakademik#1]
Push ke sini aja databasenya apa bedanya sama PM, disini untuk kontribusi bro

**Comment by zhiephie** [comment]
maybe, ada dua alernatif full version atau yang free #Opini

**Comment by feryardiant** [comment]
kalem bang, lagi ngurusin PM dia.. :sweat_smile:

**Comment by SunDi3yansyah** [comment]
:dancer: nunggu author nya datang ah

**Comment by nurisakbar** [comment]
Udah tak posting di status fb bro
Kufikir g banyak yang min at eh rupanya hampir 700 inbox masuk

Ha ha ha
Besok db nya dipush

**Comment by feryardiant** [comment]
> Ha ha ha
> Besok db nya dipush

udah masuk _besok_ bang

**Comment by SunDi3yansyah** [comment]
> udah masuk besok bang

udah 2 hari malah :joy: masih banyak PM yang harus di balas :grin:

**Comment by haqimkq** [comment]
Apakah db nya sudah ada??

**Comment by zhiephie** [comment]
wadaw sudah 2019 ini :smile:

**Comment by SunDi3yansyah** [comment]
:smile: :smile: :smile: :smile: :smile: :smile:
